apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8008
        env:
        - name: MongoDBSettings__Host
          value: mongo
        - name: MongoDBSettings__Password
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health
            port: 8008

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8008
    targetPort: 8008
